name: pgf-example
channels:
  - conda-forge
dependencies:
  - python=3.10
  - git
  - pip
  - pre-commit
  - rioxarray
  - xarray
  - pip:
      - git+https://github.com/norlandrhagen/pangeo-forge-recipes@ndpyramid
      - ndpyramid @ git+https://github.com/carbonplan/ndpyramid@split-levels
      - git+https://github.com/pangeo-forge/pangeo-forge-runner
      - git+https://github.com/leap-stc/data-management-utils
      - "apache-beam[interactive, dataframe]"
